[package]
name = "bonfire-client"
version = "0.1.0"
edition = "2021"
build = true

[dependencies]
dotenv_codegen = "0.15.0"
prost = "0.13.3"
tokio = { version = "1.40.0", features = ["full"] }
tonic = "0.12.3"
users = "0.11.0"

[build-dependencies]
tonic-build = "0.12.3"
